version: '2'

networks:
  poc:
    driver: bridge

services:
  kafka:
    image: spotify/kafka
    networks:
      - poc
    env_file: ./infra/kafka.env
    ports:
      - 2181:2181
      - 9092:9092
  schema_registry:
    image: confluentinc/cp-schema-registry
    networks: 
     - poc
    env_file: ./infra/schema_registry.env
    ports:
      - 8081:8081
    depends_on:
      - kafka
  kafka_rest:
    image: confluentinc/cp-kafka-rest
    networks: 
      - poc
    env_file: ./infra/kafka_rest.env
    ports:
      - 8082:8082
    depends_on:
     - kafka
  scripts:
    build: .
    tty: true
    volumes:
      - ./:/poc
    networks:
      - poc
    depends_on:
      - schema_registry